### ISSUE TITLE
2 or more entities in 1 app

### ISSUE THREAD

**Issue by Trychlik** [arfoll/ha-awtrix-blueprints#1]
firstly thanks for this, works perfectly
but is it possible to add more entities and texts to 1 app?
for example: text1 entity1 text2 entity2 etc

**Comment by arfoll** [comment]
Nice to know there's another user!

I feel it makes the configuration really complex if you start doing this, why not just make multiple apps for all your entities? Tbh I don't really understand the logic of the awtrix API with the 'apps', for me it makes more sense to just have notifications because HA has the data and awtrix is just a screen (at least in the way I see my setup).

I actually use this all the time, but truth be told, my setup is ultra simple and just has three apps that cycle through, and due to the  licensing conflict on the awtrix code base i'm not too keen on supporting the project...

**Comment by Trychlik** [comment]
im using a lot of apps so its more effective to cycling time
i found a workaround, its possible to create helper type template and join multiple entities

sensor:
  - platform: template
    sensors:
      combined_entity:
        value_template: "{{ states('sensor.entity1') ~ ' text2 blabla ' ~ states('sensor.entity2') }}"
